# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Download dependencies
      run: go mod download

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version:  v1.57.2 # Or another version supporting Go 1.25

    - name: Verify dependencies
      run: |
        go mod tidy
        git diff --exit-code

    # - name: golangci-lint
    #   uses: golangci/golangci-lint-action@v6
    #   with:
    #     version: latest
    #     args: --timeout=5m

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o switch-monitor-amd64 ./cmd/switch-monitor
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o switch-monitor-arm64 ./cmd/switch-monitor

    - name: Test
      run: go test -v ./...

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: switch-monitor-binaries
        path: |
          switch-monitor-amd64
          switch-monitor-arm64


